const express = require('express');
const fs = require('fs').promises;
const path = require('path');

const router = express.Router();

router.post('/', async (req, res) => {
    try {
        const { userId, styles } = req.body;
        
        if (!userId || !styles) {
            return res.status(400).json({ error: 'userId and styles required' });
        }
        
        // Ensure directory exists
        const dir = path.join(__dirname, `../../prospects/${userId}`);
        await fs.mkdir(dir, { recursive: true });
        
        // Generate CSS content
        const css = `/* Auto-generated by NITYA - StarterNode Lead Design Consultant */
/* Client: ${userId} */
/* Generated: ${new Date().toISOString()} */

:root {
    /* Brand Colors */
    --primary: ${styles.primaryColor || '#440DC3'};
    --secondary: ${styles.secondaryColor || '#00bf63'};
    
    /* Typography */
    --font-heading: '${styles.fontHeading || 'system-ui'}', sans-serif;
    --font-body: '${styles.fontBody || 'system-ui'}', sans-serif;
}

/* Reference Site: ${styles.referenceUrl || 'None provided'} */
/* Style Notes: ${styles.styleNotes || 'No additional notes'} */
`;
        
        // Write styles.css
        const filePath = path.join(dir, 'styles.css');
        await fs.writeFile(filePath, css);
        
        console.log(`✅ Styles updated for ${userId}`);
        res.json({ success: true, styles });
        
    } catch (error) {
        console.error('❌ Error updating styles:', error);
        res.status(500).json({ error: error.message });
    }
});

module.exports = router;
